{
    "file_information": {
        "file_name": "LDPE.comp",
        "file_type": "matl_usr",
        "spekpy_version": "0.0.3",
        "comment": null
    },
    "composition": {
        "density": 1,
        "number_of_elements": 2,
        "elements": [
            [
                1,
                0.14371549482137155
            ],
            [
                6,
                0.8562845051786285
            ]
        ]
    }
}