{
    "file_information": {
        "file_name": "Polystyrene.comp",
        "file_type": "matl_usr",
        "spekpy_version": "0.0.3",
        "comment": null
    },
    "composition": {
        "density": 1,
        "number_of_elements": 2,
        "elements": [
            [
                1,
                0.07742104963998606
            ],
            [
                6,
                0.9225789503600139
            ]
        ]
    }
}