{
    "file_information": {
        "file_name": "Protein.comp",
        "file_type": "matl_usr",
        "spekpy_version": "0.0.3",
        "comment": null
    },
    "composition": {
        "density": 1.35,
        "number_of_elements": 5,
        "elements": [
            [
                1,
                0.07091370055470338
            ],
            [
                6,
                0.531468478246585
            ],
            [
                7,
                0.16114200367819909
            ],
            [
                8,
                0.22654371548369764
            ],
            [
                16,
                0.009932102036815002
            ]
        ]
    }
}